name: Build

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  # Test job
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '^1.20'

      - name: Install dependencies
        run: go mod tidy

      - name: Run tests
        run: go test ./... -coverprofile=coverage.txt

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
  # Linter job
  golangci:
    name: Linter
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version: stable
      - name: golangci-lint

        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.63
  # Tag job
  tag:
    name: Tag
    runs-on : ubuntu-latest
    needs:
      - golangci
      - test
    steps:
      - name: Get Next Version
        id: semver
        uses: ietf-tools/semver-action@v1
        with:
          token: ${{ github.token }}
          branch: main

      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Tag Repo
        run: git tag -a v${{ steps.semver.outputs.next_version }} -m "Release v${{ steps.semver.outputs.next_version }}"

      - name: Push Tag
        run: git push origin v${{ steps.semver.outputs.next_version }}
